### ISSUE TITLE
Program running problem using C# API

### ISSUE THREAD

**Issue by comeCU** [MicrosoftDocs/azure-docs.zh-cn#102]
[When I used this C# API on visual studio2017, he threw these exceptions, I was very confused and hoped to give me some help. Here are some exception screenshots:]
---
#### 
![01](https://user-images.githubusercontent.com/30254171/43833361-0cc2e0ec-9b3d-11e8-9792-800d7b90314a.png)
![02](https://user-images.githubusercontent.com/30254171/43833391-29fa873c-9b3d-11e8-99d7-7abcbd532314.png)
![03](https://user-images.githubusercontent.com/30254171/43833398-2ebb2b64-9b3d-11e8-8d42-ccabddb195e0.png)

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 021ecbd2-8976-64a4-ca95-0009a1c02692
* Version Independent ID: 47011e64-0198-6fac-cd07-0334f350f59c
* Content: [使用自定义影像服务预测终结点 - Azure 认知服务](https://docs.microsoft.com/zh-cn/azure/cognitive-services/custom-vision-service/use-prediction-api)
* Content Source: [articles/cognitive-services/Custom-Vision-Service/use-prediction-api.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/cognitive-services/Custom-Vision-Service/use-prediction-api.md)
* Service: **cognitive-services**
* GitHub Login: @anrothMSFT
* Microsoft Alias: **anroth**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #13099](https://github.com/MicrosoftDocs/azure-docs/issues/13099) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @comeCU,

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here https://docs.microsoft.com/zh-cn/azure/cognitive-services/custom-vision-service/use-prediction-api

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
