### ISSUE TITLE
Please help to update China is not supported for invoice payment.

### ISSUE THREAD

**Issue by yuchiehchang** [MicrosoftDocs/azure-docs.zh-cn#104]
[Issue]
Currently, Global Azure in China is not supported in invoice payment type.

TSG: 4089458 
 

[Update Need]
Please help to make note: China in global Azure is not support in invoice payment type
•	https://docs.microsoft.com/zh-cn/azure/billing/billing-how-to-pay-by-invoice

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #13380](https://github.com/MicrosoftDocs/azure-docs/issues/13380) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @yuchiehchang , 
 
Your contribution is much appreciated. Your feedback is related to the original documentation. 
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/13380. 
 
We truly appreciate your contribution to our articles.  
 
Kind regards, 
Microsoft DOCS International Team
