### ISSUE TITLE
Only TTS has Python example.STT no have，Use REST API

### ISSUE THREAD

**Issue by SingeCore** [MicrosoftDocs/azure-docs.zh-cn#157]
In STT, I only saw TTS Python example on GitHub, no STT example, when I wrote REST API STT code with python, there were many problems URI did not respond. I asked engineers to give an example. Thank you!

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #19327](https://github.com/MicrosoftDocs/azure-docs/issues/19327) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @SingeCore,

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/19327.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
