### ISSUE TITLE
run.log() is not working inside of loops

### ISSUE THREAD

**Issue by DeMoriarty** [MicrosoftDocs/azure-docs.zh-cn#361]
for i in range(100):
    run.log('loss',loss)
this doesn't work, however,
run.log('Final loss', final_loss)
works properly.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 9190938a-63d6-5b03-ff00-9bc3bf31e27f
* Version Independent ID: 6e9f9c7d-69c3-0a20-f94f-710771255ec6
* Content: [跟踪试验和训练指标 - Azure Machine Learning service](https://docs.microsoft.com/zh-cn/azure/machine-learning/service/how-to-track-experiments)
* Content Source: [articles/machine-learning/service/how-to-track-experiments.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/machine-learning/service/how-to-track-experiments.md)
* Service: **machine-learning**
* GitHub Login: @heatherbshapiro
* Microsoft Alias: **hshapiro**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #25196](https://github.com/MicrosoftDocs/azure-docs/issues/25196) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @DeMoriarty 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/25196

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
