### ISSUE TITLE
文档中Set up your development environment被部分被漏翻译

### ISSUE THREAD

**Issue by saraao** [MicrosoftDocs/azure-docs.zh-cn#364]
文档中Set up your development environment被部分被漏翻译

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 68a3df81-6871-c443-c413-16bb97982bd4
* Version Independent ID: 5030fc51-ec28-d96e-fe85-a06a8fa1ce6f
* Content: [回归模型教程：自动化机器学习 - Azure Machine Learning service](https://docs.microsoft.com/zh-cn/azure/machine-learning/service/tutorial-auto-train-models)
* Content Source: [articles/machine-learning/service/tutorial-auto-train-models.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/machine-learning/service/tutorial-auto-train-models.md)
* Service: **machine-learning**
* GitHub Login: @nacharya1
* Microsoft Alias: **nilesha**

**Comment by CeciAc** [comment]
你好，@
saraao
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #25979](https://github.com/MicrosoftDocs/azure-docs/issues/25979) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @saraao 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/25979

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
