### ISSUE TITLE
Out of date docs

### ISSUE THREAD

**Issue by phoenixchris** [MicrosoftDocs/azure-docs.zh-cn#375]
Starting in December 2018, the Azure PowerShell Az module is in general release and now the intended PowerShell module for interacting with Azure.
This series of docs still use PowerShell AzureRM module.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: c3b89f0b-2115-efe6-e79b-946805a4283b
* Version Independent ID: 345ffa9e-1ddd-59f3-18b2-3ce11aa88646
* Content: [创建使用 IPv6 的面向 Internet 的负载均衡器 - PowerShell](https://docs.microsoft.com/zh-cn/azure/load-balancer/load-balancer-ipv6-internet-ps#feedback)
* Content Source: [articles/load-balancer/load-balancer-ipv6-internet-ps.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/load-balancer/load-balancer-ipv6-internet-ps.md)
* Service: **load-balancer**
* GitHub Login: @KumudD
* Microsoft Alias: **kumud**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #27434](https://github.com/MicrosoftDocs/azure-docs/issues/27434) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @phoenixchris 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/27434

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
