### ISSUE TITLE
deploy.ps1 is not digital signed

### ISSUE THREAD

**Issue by jznling** [MicrosoftDocs/azure-docs.zh-cn#507]
In " Deploy industrial IoT services to Azure " part, there is an error that showed "deploy.ps1 is not digitally signed". The problem can be solved by command "Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass". Please add to the potential error check part. 

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 7e60f086-ecba-acb3-c536-e101359a44bb
* Version Independent ID: 9ee3715b-2dae-9382-e484-04e8bb012818
* Content: [如何将 OPC 孪生模块部署到现有的 Azure 项目](https://docs.microsoft.com/zh-cn/azure/iot-accelerators/howto-opc-twin-deploy-existing#feedback)
* Content Source: [articles/iot-accelerators/howto-opc-twin-deploy-existing.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/iot-accelerators/howto-opc-twin-deploy-existing.md)
* Service: **iot-industrialiot**
* GitHub Login: @dominicbetts
* Microsoft Alias: **dobett**

**Comment by CeciAc** [comment]
Hello, @jznling

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/33202

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
