### ISSUE TITLE
where are the python code?

### ISSUE THREAD

**Issue by haohuancheng** [MicrosoftDocs/azure-docs.zh-cn#538]
I can not found any python code in this page: 
https://docs.microsoft.com/zh-cn/azure/iot-central/howto-connect-raspberry-pi-python

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: f9195da5-634f-e46f-4af3-4e8e1b7c4690
* Version Independent ID: a82ddd98-db6f-7ad7-58f1-2c7f46b06706
* Content: [将 Raspberry Pi 连接到 Azure IoT Central 应用程序 (Python)](https://docs.microsoft.com/zh-cn/azure/iot-central/howto-connect-raspberry-pi-python)
* Content Source: [articles/iot-central/howto-connect-raspberry-pi-python.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/iot-central/howto-connect-raspberry-pi-python.md)
* Service: **iot-central**
* GitHub Login: @dominicbetts
* Microsoft Alias: **dobett**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #33760](https://github.com/MicrosoftDocs/azure-docs/issues/33760) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @haohuancheng

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/33760

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
