### ISSUE TITLE
Can not connect to Azure SQL by this document.

### ISSUE THREAD

**Issue by siwlv** [MicrosoftDocs/azure-docs.zh-cn#546]
connection.Open() will met an Exception under .net core. How to fix it?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 3e8486cc-40d4-7bca-84e0-e4156a28fe0d
* Version Independent ID: d6e95100-d7fd-2951-366d-f4ed73ce5771
* Content: [使用 .NET Core 查询 Azure SQL 数据库](https://docs.microsoft.com/zh-cn/azure/sql-database/sql-database-connect-query-dotnet-core#feedback)
* Content Source: [articles/sql-database/sql-database-connect-query-dotnet-core.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/sql-database/sql-database-connect-query-dotnet-core.md)
* Service: **sql-database**
* Sub-service: **development**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #33942](https://github.com/MicrosoftDocs/azure-docs/issues/33942) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @https://github.com/MicrosoftDocs/azure-docs/issues/33942

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/33942

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
