### ISSUE TITLE
Deployment failed

### ISSUE THREAD

**Issue by lizkca** [MicrosoftDocs/azure-docs.zh-cn#581]
Gen4 hardware is not supported for this region.

**Comment by lichasu** [comment]
Hello, @lizkca

We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 

Kind regards, 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @lizkca
 
We are following up on our previous comment. We need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @lizkca
 
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team
