### ISSUE TITLE
Can I use Bash in Azure Cloud Shell to create a new Azure virtual machine from an Android laptop?

### ISSUE THREAD

**Issue by Sannioy** [MicrosoftDocs/azure-docs.zh-cn#675]
This is an examination question. I answered “YES”, but the correct answer is "No", I want to know why.
Looking forward to your reply. Thanks

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a60d96f9-f869-b3e9-fe07-94b53bd1f136
* Version Independent ID: 5c5bff37-d707-9220-53c1-bc1fe35eef6d
* Content: [Azure Cloud Shell 快速入门-Bash](https://docs.microsoft.com/zh-cn/azure/cloud-shell/quickstart#feedback)
* Content Source: [articles/cloud-shell/quickstart.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/cloud-shell/quickstart.md)
* Service: **azure**
* GitHub Login: @maertendMSFT
* Microsoft Alias: **damaerte**

**Comment by srvbpigh** [comment]
Hello, @Sannioy
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #43750](https://github.com/MicrosoftDocs/azure-docs/issues/43750) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @Sannioy 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/43750

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
