### ISSUE TITLE
缺少步骤,Missing a step

### ISSUE THREAD

**Issue by ngelll** [MicrosoftDocs/azure-docs.zh-cn#683]
删除即时恢复点前需要先解除分配虚拟机。You need to unallocate the virtual machine before deleting the instant recovery points.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a89ac262-76f7-45fd-d1ab-3a8702167483
* Version Independent ID: 5de7689c-dde8-6e0f-ceb4-b9c509dd57ef
* Content: [将 Azure Vm 移到新的订阅或资源组](https://docs.microsoft.com/zh-cn/azure/azure-resource-manager/management/move-limitations/virtual-machines-move-limitations#feedback)
* Content Source: [articles/azure-resource-manager/management/move-limitations/virtual-machines-move-limitations.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/azure-resource-manager/management/move-limitations/virtual-machines-move-limitations.md)

**Comment by srvbpigh** [comment]
Hello, @ngelll
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #47958](https://github.com/MicrosoftDocs/azure-docs/issues/47958) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @ngelll, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/47958. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
