### ISSUE TITLE
other param support？

### ISSUE THREAD

**Issue by linkcoder** [MicrosoftDocs/azure-docs.zh-cn#686]
rest api return InitialSilenceTimeout，how can i change this args

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 11673bc9-9062-278d-c5b8-84b05f2b81be
* Version Independent ID: 29347a63-de63-4ff0-5a62-149ab31d1b7e
* Content: [语音到文本 API 参考（REST）-语音服务 - Azure Cognitive Services](https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/rest-speech-to-text#feedback)
* Content Source: [articles/cognitive-services/Speech-Service/rest-speech-to-text.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/cognitive-services/Speech-Service/rest-speech-to-text.md)
* Service: **cognitive-services**
* Sub-service: **speech-service**
* GitHub Login: @erhopf
* Microsoft Alias: **erhopf**

**Comment by srvbpigh** [comment]
Hello, @linkcoder
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [MicrosoftDocs/azure-docs #48381](https://github.com/MicrosoftDocs/azure-docs/issues/48381) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @linkcoder, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/48381. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
