### ISSUE TITLE
[Question] How to grant permission from admin

### ISSUE THREAD

**Issue by lzw-all-in** [MicrosoftDocs/azure-docs.zh-cn#703]
Hi teams,

I'm an intern at Microsoft. I want to build an application for others to get ADL access token. I already add ADL API to my app. But it need to be grant permission from admin. How can my app be authorized by admin. I don't know who are the admin I can send email to apply this permission.

Thanks !

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 0ac43307-75d4-cb6f-e561-0dd9008f28c6
* Version Independent ID: 8fc47e76-5ee1-6aeb-73e2-c64c44e3e4ed
* Content: [Microsoft 标识平台范围、权限和同意](https://docs.microsoft.com/zh-cn/azure/active-directory/develop/v2-permissions-and-consent#feedback)
* Content Source: [articles/active-directory/develop/v2-permissions-and-consent.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/active-directory/develop/v2-permissions-and-consent.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @rwike77
* Microsoft Alias: **ryanwi**

**Comment by srvbpigh** [comment]
Hello, @lzw-all-in
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #50283](https://github.com/MicrosoftDocs/azure-docs/issues/50283) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @lzw-all-in, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/50283. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
