### ISSUE TITLE
Can container use local disk on VM in AKS node pool?

### ISSUE THREAD

**Issue by CodingXCat** [MicrosoftDocs/azure-docs.zh-cn#715]
Can container use local disk on VM in AKS node pool or using K8s hostdisk mount?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 724d659c-dcc8-7c77-1994-b3e8cc62eb8f
* Version Independent ID: f6c82819-267b-6d05-fb0b-ced6f4eb5ca3
* Content: [概念 - Azure Kubernetes 服务 (AKS) 中的存储](https://docs.microsoft.com/zh-cn/azure/aks/concepts-storage#persistent-volume-claims)
* Content Source: [articles/aks/concepts-storage.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/aks/concepts-storage.md)

**Comment by srvbpigh** [comment]
Hello, @CodingXCat
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #52410](https://github.com/MicrosoftDocs/azure-docs/issues/52410) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @CodingXCat, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/52410. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
