### ISSUE TITLE
Can AKS create deployment using Azure Disk?

### ISSUE THREAD

**Issue by CodingXCat** [MicrosoftDocs/azure-docs.zh-cn#717]
Can AKS create deployment other than pod using Azure Disk?
I want to create N pods in a deployment and each one mount a Azure Disk for itself. Can I do this?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: d1ac572f-c613-71fc-580a-2805b740b793
* Version Independent ID: b4aeef15-7b0f-abc7-872e-28051e10d6ca
* Content: [动态创建 Azure 磁盘卷 - Azure Kubernetes Service](https://docs.microsoft.com/zh-cn/azure/aks/azure-disks-dynamic-pv#create-a-persistent-volume-claim)
* Content Source: [articles/aks/azure-disks-dynamic-pv.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/aks/azure-disks-dynamic-pv.md)
* GitHub Login: @olprod

**Comment by srvbpigh** [comment]
Hello, @CodingXCat
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #53282](https://github.com/MicrosoftDocs/azure-docs/issues/53282) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @CodingXCat, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/53282. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
