### ISSUE TITLE
link of “开发模式和 USB 调试”  is "service unavailable"

### ISSUE THREAD

**Issue by coco-1998-2** [MicrosoftDocs/azure-docs.zh-cn#726]
https://developer.android.com/studio/debug/dev-options, not working

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 064d7074-3ea4-21e4-60b4-b09976bbdf7e
* Version Independent ID: 1fdefc18-e765-9fe8-0652-ca18122cb0fa
* Content: [快速入门：将语音合成到扬声器 - 语音服务 - Azure Cognitive Services](https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/quickstarts/text-to-speech?tabs=dotnet%2Clinux%2Candroid&pivots=programming-language-java)
* Content Source: [articles/cognitive-services/Speech-Service/quickstarts/text-to-speech.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/cognitive-services/Speech-Service/quickstarts/text-to-speech.md)
* Service: **cognitive-services**
* Sub-service: **speech-service**
* GitHub Login: @trevorbye
* Microsoft Alias: **trbye**

**Comment by srvbpigh** [comment]
Hello, @coco-1998-2
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @coco-1998-2 

We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 

I cannot reproduce this issue, the link works on my side.

Kind regards, 

Microsoft DOCS International Team

**Comment by coco-1998-2** [comment]
![image](https://user-images.githubusercontent.com/41716753/82407638-4b78b900-9a9c-11ea-91c6-8bea2c85568a.png)
I just need VPN to visit google android doc from China, sorry for the misleading. We can just close the bug. Apologize for the mis-leading info.

**Comment by V-vafune** [comment]
Hello, @coco-1998-2 , 

Your feedback is much appreciated. We are glad to see that your experience with our documentation meets your expectations. 

We encourage you to provide your valuable feedback so that we can continue improve your experience. 

Kind regards, 

Microsoft DOCS International Team
