### ISSUE TITLE
invalid links

### ISSUE THREAD

**Issue by v-tawe** [MicrosoftDocs/azure-docs.zh-cn#731]
Links on this page returns 404.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a8971bf0-28a2-2440-fde2-f8f262fae7b4
* Version Independent ID: 3b9de397-5346-9d30-c8af-6e9f0e619f26
* Content: [网络安全中的 Microsoft 服务](https://docs.microsoft.com/zh-cn/azure/security/fundamentals/cyber-services)
* Content Source: [articles/security/fundamentals/cyber-services.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/security/fundamentals/cyber-services.md)
* Service: **security**
* Sub-service: **security-fundamentals**
* GitHub Login: @TomShinder
* Microsoft Alias: **terrylan**

**Comment by srvbpigh** [comment]
Hello, @v-tawe
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #55977](https://github.com/MicrosoftDocs/azure-docs/issues/55977) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #55978](https://github.com/MicrosoftDocs/azure-docs/issues/55978) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @v-tawe, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/55977. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
