### ISSUE TITLE
Misleading address space in screenshot

### ISSUE THREAD

**Issue by kylefu8** [MicrosoftDocs/azure-docs.zh-cn#74]
The address space for GatewaySubnet in following screenshot is unrelated with the article:
https://docs.microsoft.com/zh-cn/azure/includes/media/vpn-gateway-add-gwsubnet-rm-portal-include/addsubnetgw.png

Doc URL:
https://docs.microsoft.com/zh-cn/azure/vpn-gateway/vpn-gateway-howto-vnet-vnet-resource-manager-portal#gatewaysubnet

**Comment by CeciAc** [comment]
Hello, @kylefu8 
 
Thank you for your feedback.
We are investigating this issue. 

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @kylefu8

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here https://github.com/MicrosoftDocs/azure-docs/issues/7722

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
